# Generated by Django 5.0.2 on 2024-02-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта поставщика')),
                ('country', models.CharField(blank=True, max_length=120, null=True, verbose_name='страна нахождения поставщика')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='город нахождения поставщика')),
                ('street', models.CharField(blank=True, max_length=120, null=True, verbose_name='улица нахождения поставщика')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакт поставщика',
                'verbose_name_plural': 'контакты поставщиков',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='названия продукта')),
                ('type', models.CharField(blank=True, max_length=120, null=True, verbose_name='модель продукта')),
                ('release', models.DateField(blank=True, null=True, verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='UnionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название компании')),
                ('level_union', models.PositiveSmallIntegerField(choices=[(0, 'factory'), (1, 'retail_chain'), (2, 'sole_proprietor')], verbose_name='иерархия поставщиков')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задолжности')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail.contact', verbose_name='Адрес звена сети')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail.product', verbose_name='Продукт произведенный звеном сети')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail.unionchain', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
    ]
