# Generated by Django 5.0.2 on 2024-02-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unionchain',
            name='level_union',
            field=models.PositiveSmallIntegerField(choices=[(0, 'factory'), (1, 'retail_chain'), (2, 'sole_proprietor')], verbose_name='Уровень звена сети'),
        ),
        migrations.AlterField(
            model_name='unionchain',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название звена сети'),
        ),
        migrations.AlterField(
            model_name='unionchain',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.unionchain', verbose_name='Поставщик от звена сети'),
        ),
    ]
